version: "2.0"

instances:
  server:
    image: docker://codeberg.org/forgejo/forgejo:10.0.1
    container_name: forgejo
    restart: always
    volumes:
      - ./env_file.sh:/.singularity.d/env/env_file.sh
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    network:
      enable: false
    depends_on:
      - db

    start:
      options:
        - fakeroot
    run:
      background: true

  db:
    image: docker://mysql:8
    restart: always
    volumes:
      - ./env_file.sh:/.singularity.d/env/env_file.sh
      - ./mysql:/var/lib/mysql
    network:
      enable: false
    start:
      options:
        - fakeroot
    run:
      background: true
