version: "2.0"

networks:
  forgejo:
    external: false

instances:
  server:
    image: docker://codeberg.org/forgejo/forgejo:10.0.1
    container_name: forgejo
    restart: always
    networks:
      - forgejo
    volumes:
      - ./env_file.sh:/.singularity.d/env/env_file.sh
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
    start:
      options:
        - fakeroot
    run:
      background: true

  db:
    image: docker://mysql:8
    restart: always
    networks:
      - forgejo
    volumes:
      - ./env_file.sh:/.singularity.d/env/env_file.sh
      - ./mysql:/var/lib/mysql
    start:
      options:
        - fakeroot
    run:
      background: true
